language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - python setup.py develop
script: "py.test -svv --flake8 --cov=better tests/"
after_success:
  coveralls
deploy:
  # test pypi
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: "cmheisel"
    password:
      secure: "CBHlOYR2ma7Zf8g5jZeTA9QfUpPPM4fOjlTcHq64RRhdTpXHFEH/+ki1CPEwi8cB1jOFrds/fJ7L95ftBXN6O7eITCrHlj1Iu8u49jl6YawiGQ7GUvlYSD+zp
piZzt1VqXA9iMLZt8QF/MmyKFuFeqtROBp6i+W8aTwsXm1OLOOt3UDZuWE4j5Fis64BnXKPgeusGwpBXOEOD+RRk3f3uUmty2uXlkZycwHak5lrQM16keGi0ClZYgSFd4I0X
z9GDAQ5B3AstEihHEzqg1BJ2JYV8d1mDfOhE6Wfrj+wguayHoKa0Qb9BcSl85x5ij1hGJypfS74yPyE6ZIbGcJ3xRRlMVIgBuLour4DIG44+YhYH4pUb5BOo+7lk3LnmR8/j
oTcDUvLqSDD4shO4BGj5t3u+nQMBJvY88Iya8W7A8JLcmwVm/6b6fjKyDFb5jSK2OhV6/SPqpQW+29RT5Oro2ufWPJCMZtpYGUAgLJYPfv82Tu0N5zgLk+qCvay4CkH2V7VA
tUuhkXupaSH/zv4GAN+yebf5QV0rW7DTLo/U3Mf7COux/i0ae9qczhFkqH9aeTvP+oBA3Ji3UGgw9HvjePGh3a94V7O9kcNnmz0yToXHLTfYQaQNZtU5nBr+ReYjfGHmjxz+
Cfwc9CVx5DZbvC6gO7NNbFMFH/sXlcAAmc="
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
  # production pypi
  - provider: pypi
    user: "cmheisel"
    password:
      secure: "NC4T0/32B7nfQr95vEnY2ObQ8a8r8lfML6tqXb4V5EFAG+WlJZ5SD1OTrVBWhT3zAjqWy8D1QzuOOmXCoSYCZxgIb1FxdMxMqgi93UHKMWSroza/CmIU+Gg/f
o7SVd6KP26oMOglzUrKPBhSn0y67wpCPzM3YC2m5jhbdkBiQIQhiAqh+lTlCHuG6FOVwTI2YPElvK9wn/hHhXs7ldtwagB6v91GIfjdzpV99LjsBNhZTxPBswAvn53XfQRfB
gAYZiDhh2a4/4NNLPpxM7IHVysmyLEyPB9ChCzeDTYDlAD+MQh3BSiZjf2vnrg/WCcoJjx/YQq/2vOK6h7DKhX9HSmrSsEsJ5/9B7J9KUWeEbNCMqej39mVAXjEvsNUcHRFy
kp2F6frfccQPxHrnZMd8KXWAJQg1gWCCPSDOpmNYlT4ocxZCyDT8UzuvfJ5fX1K1CoJ0otvWytEYDn9BaWpwacNEymQS0QZNplmMpDJJ51nDd/Hwz1J6s1TsEXkrBUYXXSzr
1N458kjlnsp2DTtWmfqqa00qna/K2Aav5r0sqgEBBSxP7VINI9EO6kXRPPs1yFsIerrKwV367FDjUC9xXgSxB2q5bFKn5OU4ITNqUiJrVSs56/jAfDZv1VfvSTcJnmkiPKKZ
09INYG2/XjrR3WL9DIqkNBseYnJ3kw0eHA="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
